# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stage_service_pb2 as stage__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stage_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StageServiceStub(object):
    """Service de gestion des stages au Cameroun."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStage = channel.unary_unary(
                '/stageservice.StageService/CreateStage',
                request_serializer=stage__service__pb2.CreateStageRequest.SerializeToString,
                response_deserializer=stage__service__pb2.StageResponse.FromString,
                _registered_method=True)
        self.UpdateStage = channel.unary_unary(
                '/stageservice.StageService/UpdateStage',
                request_serializer=stage__service__pb2.UpdateStageRequest.SerializeToString,
                response_deserializer=stage__service__pb2.StageResponse.FromString,
                _registered_method=True)
        self.GetStage = channel.unary_unary(
                '/stageservice.StageService/GetStage',
                request_serializer=stage__service__pb2.GetStageRequest.SerializeToString,
                response_deserializer=stage__service__pb2.StageResponse.FromString,
                _registered_method=True)
        self.ListStages = channel.unary_unary(
                '/stageservice.StageService/ListStages',
                request_serializer=stage__service__pb2.ListStagesRequest.SerializeToString,
                response_deserializer=stage__service__pb2.ListStagesResponse.FromString,
                _registered_method=True)
        self.DeleteStage = channel.unary_unary(
                '/stageservice.StageService/DeleteStage',
                request_serializer=stage__service__pb2.DeleteStageRequest.SerializeToString,
                response_deserializer=stage__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.AssignSupervisor = channel.unary_unary(
                '/stageservice.StageService/AssignSupervisor',
                request_serializer=stage__service__pb2.AssignSupervisorRequest.SerializeToString,
                response_deserializer=stage__service__pb2.StageResponse.FromString,
                _registered_method=True)
        self.SubmitReport = channel.unary_unary(
                '/stageservice.StageService/SubmitReport',
                request_serializer=stage__service__pb2.SubmitReportRequest.SerializeToString,
                response_deserializer=stage__service__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.EvaluateStage = channel.unary_unary(
                '/stageservice.StageService/EvaluateStage',
                request_serializer=stage__service__pb2.EvaluateStageRequest.SerializeToString,
                response_deserializer=stage__service__pb2.EvaluationResponse.FromString,
                _registered_method=True)


class StageServiceServicer(object):
    """Service de gestion des stages au Cameroun."""

    def CreateStage(self, request, context):
        """Créer un nouveau stage."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStage(self, request, context):
        """Mettre à jour un stage existant."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStage(self, request, context):
        """Obtenir les détails d'un stage."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStages(self, request, context):
        """Lister les stages avec filtres."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStage(self, request, context):
        """Supprimer un stage."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignSupervisor(self, request, context):
        """Assigner un encadreur à un stage."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitReport(self, request, context):
        """Soumettre un rapport de stage."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateStage(self, request, context):
        """Évaluer un stage."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStage,
                    request_deserializer=stage__service__pb2.CreateStageRequest.FromString,
                    response_serializer=stage__service__pb2.StageResponse.SerializeToString,
            ),
            'UpdateStage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStage,
                    request_deserializer=stage__service__pb2.UpdateStageRequest.FromString,
                    response_serializer=stage__service__pb2.StageResponse.SerializeToString,
            ),
            'GetStage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStage,
                    request_deserializer=stage__service__pb2.GetStageRequest.FromString,
                    response_serializer=stage__service__pb2.StageResponse.SerializeToString,
            ),
            'ListStages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStages,
                    request_deserializer=stage__service__pb2.ListStagesRequest.FromString,
                    response_serializer=stage__service__pb2.ListStagesResponse.SerializeToString,
            ),
            'DeleteStage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStage,
                    request_deserializer=stage__service__pb2.DeleteStageRequest.FromString,
                    response_serializer=stage__service__pb2.DeleteResponse.SerializeToString,
            ),
            'AssignSupervisor': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignSupervisor,
                    request_deserializer=stage__service__pb2.AssignSupervisorRequest.FromString,
                    response_serializer=stage__service__pb2.StageResponse.SerializeToString,
            ),
            'SubmitReport': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitReport,
                    request_deserializer=stage__service__pb2.SubmitReportRequest.FromString,
                    response_serializer=stage__service__pb2.ReportResponse.SerializeToString,
            ),
            'EvaluateStage': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateStage,
                    request_deserializer=stage__service__pb2.EvaluateStageRequest.FromString,
                    response_serializer=stage__service__pb2.EvaluationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stageservice.StageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stageservice.StageService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class StageService(object):
    """Service de gestion des stages au Cameroun."""

    @staticmethod
    def CreateStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stageservice.StageService/CreateStage',
            stage__service__pb2.CreateStageRequest.SerializeToString,
            stage__service__pb2.StageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stageservice.StageService/UpdateStage',
            stage__service__pb2.UpdateStageRequest.SerializeToString,
            stage__service__pb2.StageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stageservice.StageService/GetStage',
            stage__service__pb2.GetStageRequest.SerializeToString,
            stage__service__pb2.StageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stageservice.StageService/ListStages',
            stage__service__pb2.ListStagesRequest.SerializeToString,
            stage__service__pb2.ListStagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stageservice.StageService/DeleteStage',
            stage__service__pb2.DeleteStageRequest.SerializeToString,
            stage__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignSupervisor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stageservice.StageService/AssignSupervisor',
            stage__service__pb2.AssignSupervisorRequest.SerializeToString,
            stage__service__pb2.StageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stageservice.StageService/SubmitReport',
            stage__service__pb2.SubmitReportRequest.SerializeToString,
            stage__service__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stageservice.StageService/EvaluateStage',
            stage__service__pb2.EvaluateStageRequest.SerializeToString,
            stage__service__pb2.EvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
